<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>LoadSearch.Application</AssemblyName>
    <RootNamespace>LoadSearch.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Cohesive.Relations" Version="[0.1.0-eval.coh56.8cf0242]" />
  </ItemGroup>
</Project>
